[ci] De-duplicate retry functions (#12325)

diff --git a/ci/jenkins/macros.j2 b/ci/jenkins/macros.j2
--- a/ci/jenkins/macros.j2
+++ b/ci/jenkins/macros.j2
@@ -113,23 +113,23 @@ def {{ method_name }}() {
 
 {% macro bash_retry() %}
 retry() {
-  local retries=\$1
+  local max_retries=\$1
   shift
+  local n=0
+  local backoff_max=30
+  until [ "\$n" -ge \$max_retries ]
+  do
+      "\$@" && break
+      n=\$((n+1))
+      if [ "\$n" -eq \$max_retries ]; then
+          echo "failed to update after attempt \$n / \$max_retries, giving up"
+          exit 1
+      fi
 
-  local count=0
-  until "\$@"; do
-    exit=\$?
-    wait=\$((2 ** \$count))
-    count=\$((\$count + 1))
-    if [ \$count -lt \$retries ]; then
-      echo "Retry \$count/\$retries exited \$exit, retrying in \$wait seconds..."
-      sleep \$wait
-    else
-      echo "Retry \$count/\$retries exited \$exit, no more retries left."
-      return \$exit
-    fi
+      WAIT=\$(python3 -c 'import random; print(random.randint(10, 30))')
+      echo "failed to update \$n / \$max_retries, waiting \$WAIT to try again"
+      sleep \$WAIT
   done
-  return 0
 }
 {% endmacro %}
 
